DROP TABLE if exists bookmarks;

CREATE TABLE bookmarks(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    bookmark_name VARCHAR Not NULL,
    book_id VARCHAR(36) NOT NULL,
    url VARCHAR Not NULL,
    description VARCHAR Not NULL, 
    rating VARCHAR Not NULL
);